apiVersion: v1
kund: Pod
metadata:
  name: test
spec:
  containers:
    - name: test-container
      image: rapa.iptime.org:5000/nginx:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: np-test-svc
spec:
  selector:
    app: np-test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
