apiVersion: v1
kind: Pod
metadata:
  name: np-test
  labels:
    app: np-test
spec:
  containers:
  - name: np-container
    image: rapa.iptime.org:5000/nginx:latest 
---
apiVersion: v1
kind: Service
metadata:
  name: np-test-svc
spec:
  selector:
    app: np-test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
